collections:
  posts:
    label: Posts
    folder: _posts
    create: true
    slug: "{{slug}}"
    fields:
      - label: Título
        name: title
        widget: string
      - label: Data
        name: date
        widget: datetime
      - label: Conteúdo
        name: body
        widget: markdown