content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [title, date]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: datetime
      - name: description
        label: Description
        type: text
      - name: image
        label: Image
        type: string
      - name: tags
        label: Tags
        type: array
        item_type: string
      - name: og_type
        label: og:type
        type: string
      - name: body
        label: Content
        type: markdown