content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [title, date]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: date
        label: Date
        type: datetime
      - name: body
        label: Content
        type: rich-text