name: Atualizar Posts do Bluesky via RSS

on:
  schedule:
    - cron: '0 */12 * * *' # Roda à meia-noite e ao meio-dia UTC
  workflow_dispatch:     # Permite rodar manualmente

jobs:
  update-bluesky-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install feedparser

      - name: Rodar script Python para atualizar posts do Bluesky
        run: python scripts/update_bluesky_posts.py
        env:
          BLUESKY_HANDLE: 'celozaga.bsky.social' # <-- SEU HANDLE JÁ CONFIGURADO AQUI

      - name: Commit e push dos posts novos
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/
          git commit -m "Atualizar posts do Bluesky via RSS (workflow automático)" || echo "Sem alterações para commitar"
          git push
