name: Atualizar Posts do YouTube via RSS

on:
  schedule:
    - cron: '0 0 * * 0' # todo domingo à meia-noite UTC
  workflow_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install feedparser

    - name: Buscar vídeos e gerar posts via RSS
      env:
        CHANNEL_ID: 'UCvOnTTQp_7ZXtWUZYEUZO7Q'
      run: |
        python <<EOF
        import os
        import feedparser
        from datetime import datetime

        channel_id = os.environ['CHANNEL_ID']
        rss_url = f'https://www.youtube.com/feeds/videos.xml?channel_id={channel_id}'
        posts_dir = '_posts'

        feed = feedparser.parse(rss_url)

        if not feed.entries:
            print("Nenhum vídeo encontrado no RSS.")
            exit(0)

        if not os.path.exists(posts_dir):
            os.makedirs(posts_dir)

        for entry in feed.entries:
            video_id = entry.yt_videoid
            title = entry.title.replace('/', '-')
            published = entry.published_parsed
            date_str = datetime(*published[:6]).strftime('%Y-%m-%d')
            filename = f"{date_str}-{title.lower().replace(' ', '-')}.md"
            path = os.path.join(posts_dir, filename)

            if not os.path.exists(path):
                content = f'''---
layout: post
title: "{entry.title}"
date: {date_str}
---

<h1>{entry.title}</h1>

<iframe width="560" height="315" src="https://www.youtube.com/embed/{video_id}" frameborder="0" allowfullscreen></iframe>

<p>{entry.summary}</p>
'''
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f"Criado post: {filename}")
            else:
                print(f"Post já existe: {filename}")
        EOF

    - name: Commit e push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add _posts/
        git commit -m "Atualizar posts do YouTube via RSS (workflow automático)" || echo "Sem alterações para commitar"
        git push
